const blogData = {
  categories: [
    {
      id: 0,
      name: "All",
      slug: "all",
      image: "/images/All.png",
      subcategories: [],
    },
    {
      id: 1,
      name: "Motivational",
      slug: "motivational",
      image: "/images/Motivational.png",
      subcategories: [
        "Success Stories",
        "Mental Health & Wellness",
        "Goal Setting & Planning",
        "Overcoming Challenges",
        "Personal Development",
        "Inspiration & Quotes",
      ],
    },
    {
      id: 2,
      name: "Essay",
      slug: "essay",
      image: "/images/Essay.png",
      subcategories: [
        "Essay Writing Techniques",
        "Sample Essays",
        "Topic Analysis",
        "Structure & Format",
        "Language & Style",
        "Practice Questions",
      ],
    },
    {
      id: 3,
      name: "Strategy",
      slug: "strategy",
      image: "/images/Strategy.png",
      subcategories: [
        "Study Planning",
        "Time Management",
        "Subject-wise Strategy",
        "Revision Techniques",
        "Mock Test Strategy",
        "Optional Subject Strategy",
      ],
    },
    {
      id: 4,
      name: "Current Affairs",
      slug: "current-affairs",
      image: "/images/Current Affairs.png",
      subcategories: [
        "Polity & Governance",
        "Economy & Finance",
        "Environment & Ecology",
        "International Relations & Defence",
        "Social Issues & Human Development",
        "Geography & Disaster Management",
      ],
    },
    {
      id: 5,
      name: "UPSC",
      slug: "upsc",
      image: "/images/UPSC.png",
      subcategories: [
        "Prelims Preparation",
        "Mains Preparation",
        "Interview Guidance",
        "Syllabus Analysis",
        "Previous Year Papers",
        "Notification & Updates",
      ],
    },
    {
      id: 6,
      name: "BPSC",
      slug: "bpsc",
      image: "/images/BPSC.png",
      subcategories: [
        "BPSC Prelims",
        "BPSC Mains",
        "Bihar Specific Topics",
        "Previous Year Analysis",
        "Study Material",
        "Exam Pattern",
      ],
    },
    {
      id: 7,
      name: "Essay Writing",
      slug: "essay-writing",
      image: "/images/Essay Writing.png",
      subcategories: [
        "Philosophical Essays",
        "Social Issues Essays",
        "Economic Essays",
        "Political Essays",
        "Environmental Essays",
        "Ethical Essays",
      ],
    },
  ],
  blogs: [
    {
      id: 1,
      title: "How to Stay Motivated During UPSC Preparation",
      slug: "stay-motivated-upsc-preparation",
      excerpt:
        "Discover proven strategies to maintain motivation throughout your UPSC journey and overcome preparation challenges.",
      author: "Rajesh Kumar",
      readTime: "8 Min Reading",
      publishedDate: "2025-06-20",
      category: "Motivational",
      subCategory: "Social Issues & Human Development",
      image: "/images/tempImage.jpg",
      timestamp: new Date("2025-06-20").getTime(),
    },
    {
      id: 2,
      title: "From Failure to Success: My UPSC Journey",
      slug: "failure-to-success-upsc-journey",
      excerpt:
        "A personal account of overcoming multiple failures and finally cracking UPSC. Learn from real experiences and mistakes.",
      author: "Rohit Sharma",
      readTime: "12 Min Reading",
      publishedDate: "2025-06-10",
      category: "Motivational",
      subCategory: "Social Issues & Human Development",
      image: "/images/tempImage.jpg",
      timestamp: new Date("2025-06-10").getTime(),
    },
    {
      id: 3,
      title: "Essay Writing Techniques for UPSC Mains",
      slug: "essay-writing-techniques-upsc-mains",
      excerpt: "Master the art of essay writing with proven techniques and sample essays for UPSC Mains examination.",
      author: "Anita Singh",
      readTime: "15 Min Reading",
      publishedDate: "2025-06-18",
      category: "Essay",
      subCategory: "Geography & Disaster Management",
      image: "/images/tempImage.jpg",
      timestamp: new Date("2025-06-18").getTime(),
    },
    {
      id: 4,
      title: "Answer Writing Practice for UPSC Mains",
      slug: "answer-writing-practice-upsc-mains",
      excerpt:
        "Comprehensive guide to answer writing practice with sample answers and evaluation techniques for UPSC Mains.",
      author: "Dr. Meera Joshi",
      readTime: "18 Min Reading",
      publishedDate: "2025-06-08",
      category: "Essay",
      subCategory: "Polity & Governance",
      image: "/images/tempImage.jpg",
      timestamp: new Date("2025-06-08").getTime(),
    },
    {
      id: 5,
      title: "UPSC Preparation Strategy for Working Professionals",
      slug: "upsc-strategy-working-professionals",
      excerpt:
        "Effective preparation strategies for working professionals aspiring to crack UPSC while managing job responsibilities.",
      author: "Vikram Patel",
      readTime: "10 Min Reading",
      publishedDate: "2025-06-15",
      category: "Strategy",
      subCategory: "Environment & Ecology",
      image: "/images/tempImage.jpg",
      timestamp: new Date("2025-06-15").getTime(),
    },
    {
      id: 6,
      title: "Time Management Strategies for UPSC Success",
      slug: "time-management-strategies-upsc",
      excerpt:
        "Learn effective time management techniques to optimize your UPSC preparation and maximize productivity.",
      author: "Priya Gupta",
      readTime: "9 Min Reading",
      publishedDate: "2025-06-05",
      category: "Strategy",
      subCategory: "Economy & Finance",
      image: "/images/tempImage.jpg",
      timestamp: new Date("2025-06-05").getTime(),
    },
    {
      id: 7,
      title: "Budget 2024: Key Reforms for UPSC Aspirants",
      slug: "budget-2024-key-reforms-upsc-aspirants",
      excerpt: "Analysis of new tax reforms, education policies, and their GS Paper 3 implications.",
      author: "Priya Sharma",
      readTime: "5 Min Reading",
      publishedDate: "26/6/2025",
      category: "Current Affairs",
      subCategory: "Economy & Finance",
      image: "/images/tempImage.jpg",
      timestamp: new Date("2025-06-26").getTime(),
    },
    {
      id: 8,
      title: "UPSC 2025 Notification Out - Complete Guide",
      slug: "upsc-2025-notification-complete-guide",
      excerpt:
        "UPSC Notification 2025 was released on 22nd January 2025 that marks beginning of Application Process. Get complete details here.",
      author: "Priya Sharma",
      readTime: "12 Min Reading",
      publishedDate: "21/6/2025",
      category: "Current Affairs",
      subCategory: "Polity & Governance",
      image: "/images/tempImage.jpg",
      timestamp: new Date("2025-06-21").getTime(),
    },
    {
      id: 9,
      title: "UPSC Prelims Result 2025 - What's Next?",
      slug: "upsc-prelims-result-2025-whats-next",
      excerpt:
        "UPSC Prelims Result 2025 is out. Get the PDF link, check roll numbers, and know the next steps for Mains preparation.",
      author: "Priya Sharma",
      readTime: "6 Min Reading",
      publishedDate: "12/6/2025",
      category: "Current Affairs",
      subCategory: "International Relations & Defence",
      image: "/images/tempImage.jpg",
      timestamp: new Date("2025-06-12").getTime(),
    },
  ],
}

export default blogData
